name: .NET Core
on:
  push:
    branches: [main]

jobs: 
  publish-packages:
    name: publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: clean
        run: |
          dotnet clean
          dotnet nuget locals all --clear
      - name: test
        run: dotnet test
      - name: build
        run: dotnet build --configuration Release
      - name: publish
        run: |
          dotnet nuget push "*/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key  ${{ secrets.NugetKey }} 
