name: .NET Core
on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    name: 发布包
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 初始dotnet环境
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: 运行测试
        run: dotnet test
      - name: 还原包
        run: dotnet restore
      - name: 部署
        run: dotnet build --configuration Release --no-restore
      - name: 初始nuget环境
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"
      - name: 发布nuget包
        run: |
          nuget push */bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
