name: .NET Core
on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    name: 发布包
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 初始dotnet环境
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: 运行测试
        run: dotnet test
      - name: 还原包
        run: dotnet restore
      - name: 构建
        run: dotnet build --configuration Release --no-restore
      - name: 发布包到nuget
        run: |
          dotnet nuget push "*/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key  ${{ secrets.NugetKey }} 
